[package]
name = "rust-elo-multiplayer"
version = "0.1.0"
edition = "2021"
description = "Calculate ELO with multiple players"
authors = ["Mattias Mucherie"]
license = "MIT"
keywords = ["elo", "multiplayer"]
[dependencies]
